if GGWTest == nill then GGWTest = {} end

GGWTest.Strings =
{
    tempDevCastString = "You casted %s (%s), this spell is not being tracked ATM! (Temporary Message).",
    YouCastedSelf     = "You casted Rank %d %s (%s) as a level %s",
    YouCastedTarget   = "You casted Rank %d %s (%s) on a level %s target",
    UseHigher         = ", you should be using a higher rank!",
}

GGWTest.SpellIDs =
{
    -- Warrior
    -- Paladin
    -- Hunter
    -- Rogue
    -- Priest
    -- Shaman
    -- Mage
    -- Warlock
    -- Druid
    [ 2893] = {Name =              "Abolish Poison", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [22812] = {Name =                    "Barkskin", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 5211] = {Name =                        "Bash", Rank =  1, MaxLevel = 29, LevelBase =   "Self",},
    [ 6798] = {Name =                        "Bash", Rank =  2, MaxLevel = 45, LevelBase =   "Self",},
    [ 8983] = {Name =                        "Bash", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [33009] = {Name =              "Blinding Light", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [25999] = {Name =                 "Boar Charge", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [33908] = {Name =              "Burning Spikes", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 1082] = {Name =                        "Claw", Rank =  1, MaxLevel = 27, LevelBase =   "Self",},
    [31289] = {Name =                        "Claw", Rank =  1, MaxLevel = 27, LevelBase =   "Self",},
    [ 3029] = {Name =                        "Claw", Rank =  2, MaxLevel = 37, LevelBase =   "Self",},
    [ 5201] = {Name =                        "Claw", Rank =  3, MaxLevel = 47, LevelBase =   "Self",},
    [ 9849] = {Name =                        "Claw", Rank =  4, MaxLevel = 57, LevelBase =   "Self",},
    [ 9850] = {Name =                        "Claw", Rank =  5, MaxLevel = 66, LevelBase =   "Self",},
    [27000] = {Name =                        "Claw", Rank =  6, MaxLevel =  0, LevelBase =   "Self",},
    [16870] = {Name =                "Clearcasting", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [34071] = {Name =                 "Combo Point", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [32618] = {Name =        "Cosmetic Nature Cast", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [38326] = {Name = "Crit Threat Reduction Melee", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [38327] = {Name = "Crit Threat Reduction Spell", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 8946] = {Name =                 "Cure Poison", Rank =  1, MaxLevel = 25, LevelBase =   "Self",},
    [33786] = {Name =                     "Cyclone", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [   99] = {Name =           "Demoralizing Roar", Rank =  1, MaxLevel = 19, LevelBase =   "Self",},
    [ 1735] = {Name =           "Demoralizing Roar", Rank =  2, MaxLevel = 31, LevelBase =   "Self",},
    [ 9490] = {Name =           "Demoralizing Roar", Rank =  3, MaxLevel = 41, LevelBase =   "Self",},
    [ 9747] = {Name =           "Demoralizing Roar", Rank =  4, MaxLevel = 51, LevelBase =   "Self",},
    [ 9898] = {Name =           "Demoralizing Roar", Rank =  5, MaxLevel = 61, LevelBase =   "Self",},
    [26998] = {Name =           "Demoralizing Roar", Rank =  6, MaxLevel =  0, LevelBase =   "Self",},
    [25059] = {Name =                  "Dmg Shield", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [26666] = {Name =                 "Dmg Shield2", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 5229] = {Name =                      "Enrage", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [  339] = {Name =            "Entangling Roots", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [19975] = {Name =            "Entangling Roots", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [40363] = {Name =            "Entangling Roots", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 1062] = {Name =            "Entangling Roots", Rank =  2, MaxLevel =  0, LevelBase =   "Self",},
    [19974] = {Name =            "Entangling Roots", Rank =  2, MaxLevel =  0, LevelBase =   "Self",},
    [ 5195] = {Name =            "Entangling Roots", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [19973] = {Name =            "Entangling Roots", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [ 5196] = {Name =            "Entangling Roots", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [19972] = {Name =            "Entangling Roots", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [ 9852] = {Name =            "Entangling Roots", Rank =  5, MaxLevel =  0, LevelBase =   "Self",},
    [19971] = {Name =            "Entangling Roots", Rank =  5, MaxLevel =  0, LevelBase =   "Self",},
    [ 9853] = {Name =            "Entangling Roots", Rank =  6, MaxLevel =  0, LevelBase =   "Self",},
    [19970] = {Name =            "Entangling Roots", Rank =  6, MaxLevel =  0, LevelBase =   "Self",},
    [26989] = {Name =            "Entangling Roots", Rank =  7, MaxLevel =  0, LevelBase =   "Self",},
    [27010] = {Name =            "Entangling Roots", Rank =  7, MaxLevel =  0, LevelBase =   "Self",},
    [27546] = {Name =          "Faerie Dragon Form", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [  770] = {Name =                 "Faerie Fire", Rank =  1, MaxLevel = 29, LevelBase =   "Self",},
    [  778] = {Name =                 "Faerie Fire", Rank =  2, MaxLevel = 41, LevelBase =   "Self",},
    [ 9749] = {Name =                 "Faerie Fire", Rank =  3, MaxLevel = 53, LevelBase =   "Self",},
    [ 9907] = {Name =                 "Faerie Fire", Rank =  4, MaxLevel = 65, LevelBase =   "Self",},
    [26993] = {Name =                 "Faerie Fire", Rank =  5, MaxLevel =  0, LevelBase =   "Self",},
    [16857] = {Name =         "Faerie Fire (Feral)", Rank =  1, MaxLevel = 29, LevelBase =   "Self",},
    [17390] = {Name =         "Faerie Fire (Feral)", Rank =  2, MaxLevel = 41, LevelBase =   "Self",},
    [17391] = {Name =         "Faerie Fire (Feral)", Rank =  3, MaxLevel = 53, LevelBase =   "Self",},
    [17392] = {Name =         "Faerie Fire (Feral)", Rank =  4, MaxLevel = 65, LevelBase =   "Self",},
    [27011] = {Name =         "Faerie Fire (Feral)", Rank =  5, MaxLevel =  0, LevelBase =   "Self",},
    [38333] = {Name =                   "Fecundity", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [16979] = {Name =                "Feral Charge", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [19675] = {Name =         "Feral Charge Effect", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [45334] = {Name =         "Feral Charge Effect", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [24867] = {Name =  "Feral Swiftness Passive 1a", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [24864] = {Name =  "Feral Swiftness Passive 2a", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [22568] = {Name =              "Ferocious Bite", Rank =  1, MaxLevel = 39, LevelBase =   "Self",},
    [22827] = {Name =              "Ferocious Bite", Rank =  2, MaxLevel = 47, LevelBase =   "Self",},
    [22828] = {Name =              "Ferocious Bite", Rank =  3, MaxLevel = 55, LevelBase =   "Self",},
    [22829] = {Name =              "Ferocious Bite", Rank =  4, MaxLevel = 59, LevelBase =   "Self",},
    [31018] = {Name =              "Ferocious Bite", Rank =  5, MaxLevel = 62, LevelBase =   "Self",},
    [24248] = {Name =              "Ferocious Bite", Rank =  6, MaxLevel =  0, LevelBase =   "Self",},
    [33831] = {Name =             "Force of Nature", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [22842] = {Name =       "Frenzied Regeneration", Rank =  1, MaxLevel = 45, LevelBase =   "Self",},
    [22895] = {Name =       "Frenzied Regeneration", Rank =  2, MaxLevel = 55, LevelBase =   "Self",},
    [22896] = {Name =       "Frenzied Regeneration", Rank =  3, MaxLevel = 64, LevelBase =   "Self",},
    [26999] = {Name =       "Frenzied Regeneration", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [21849] = {Name =            "Gift of the Wild", Rank =  1, MaxLevel = 59, LevelBase =   "Self",},
    [21850] = {Name =            "Gift of the Wild", Rank =  2, MaxLevel = 69, LevelBase =   "Self",},
    [26991] = {Name =            "Gift of the Wild", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [ 6795] = {Name =                       "Growl", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [39270] = {Name =                       "Growl", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 5185] = {Name =               "Healing Touch", Rank =  1, MaxLevel =  7, LevelBase =   "Self",},
    [ 5186] = {Name =               "Healing Touch", Rank =  2, MaxLevel =  0, LevelBase =   "Self",},
    [ 5187] = {Name =               "Healing Touch", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [ 5188] = {Name =               "Healing Touch", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [ 5189] = {Name =               "Healing Touch", Rank =  5, MaxLevel =  0, LevelBase =   "Self",},
    [ 6778] = {Name =               "Healing Touch", Rank =  6, MaxLevel =  0, LevelBase =   "Self",},
    [ 8903] = {Name =               "Healing Touch", Rank =  7, MaxLevel =  0, LevelBase =   "Self",},
    [ 9758] = {Name =               "Healing Touch", Rank =  8, MaxLevel =  0, LevelBase =   "Self",},
    [ 9888] = {Name =               "Healing Touch", Rank =  9, MaxLevel =  0, LevelBase =   "Self",},
    [ 9889] = {Name =               "Healing Touch", Rank = 10, MaxLevel =  0, LevelBase =   "Self",},
    [25297] = {Name =               "Healing Touch", Rank = 11, MaxLevel =  0, LevelBase =   "Self",},
    [26978] = {Name =               "Healing Touch", Rank = 12, MaxLevel =  0, LevelBase =   "Self",},
    [26979] = {Name =               "Healing Touch", Rank = 13, MaxLevel =  0, LevelBase =   "Self",},
    [ 2637] = {Name =                   "Hibernate", Rank =  1, MaxLevel = 37, LevelBase =   "Self",},
    [18657] = {Name =                   "Hibernate", Rank =  2, MaxLevel = 57, LevelBase =   "Self",},
    [18658] = {Name =                   "Hibernate", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [27530] = {Name =                   "Hurricane", Rank =  1, MaxLevel = 39, LevelBase =   "Self",},
    [32717] = {Name =                   "Hurricane", Rank =  1, MaxLevel = 39, LevelBase =   "Self",},
    [16914] = {Name =                   "Hurricane", Rank =  1, MaxLevel = 49, LevelBase =   "Self",},
    [42231] = {Name =                   "Hurricane", Rank =  1, MaxLevel = 49, LevelBase =   "Self",},
    [17401] = {Name =                   "Hurricane", Rank =  2, MaxLevel = 59, LevelBase =   "Self",},
    [42232] = {Name =                   "Hurricane", Rank =  2, MaxLevel = 59, LevelBase =   "Self",},
    [17402] = {Name =                   "Hurricane", Rank =  3, MaxLevel = 69, LevelBase =   "Self",},
    [42233] = {Name =                   "Hurricane", Rank =  3, MaxLevel = 69, LevelBase =   "Self",},
    [27012] = {Name =                   "Hurricane", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [42230] = {Name =                   "Hurricane", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [29166] = {Name =                   "Innervate", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 5570] = {Name =                "Insect Swarm", Rank =  1, MaxLevel = 29, LevelBase =   "Self",},
    [24974] = {Name =                "Insect Swarm", Rank =  2, MaxLevel = 39, LevelBase =   "Self",},
    [24975] = {Name =                "Insect Swarm", Rank =  3, MaxLevel = 49, LevelBase =   "Self",},
    [24976] = {Name =                "Insect Swarm", Rank =  4, MaxLevel = 59, LevelBase =   "Self",},
    [24977] = {Name =                "Insect Swarm", Rank =  5, MaxLevel = 69, LevelBase =   "Self",},
    [27013] = {Name =                "Insect Swarm", Rank =  6, MaxLevel =  0, LevelBase =   "Self",},
    [41357] = {Name =            "L1 Arcane Charge", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [41349] = {Name =            "L4 Arcane Charge", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [41360] = {Name =            "L5 Arcane Charge", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [33745] = {Name =                    "Lacerate", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [33763] = {Name =                   "Lifebloom", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [33778] = {Name =                   "Lifebloom", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [22570] = {Name =                        "Maim", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [19634] = {Name =           "Mana Rejuvenation", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [39164] = {Name =                      "Mangle", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [31041] = {Name =                      "Mangle", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [44955] = {Name =                      "Mangle", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [33878] = {Name =               "Mangle (Bear)", Rank =  1, MaxLevel = 57, LevelBase =   "Self",},
    [33986] = {Name =               "Mangle (Bear)", Rank =  2, MaxLevel = 67, LevelBase =   "Self",},
    [33987] = {Name =               "Mangle (Bear)", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [33876] = {Name =                "Mangle (Cat)", Rank =  1, MaxLevel = 57, LevelBase =   "Self",},
    [33982] = {Name =                "Mangle (Cat)", Rank =  2, MaxLevel = 67, LevelBase =   "Self",},
    [33983] = {Name =                "Mangle (Cat)", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [ 1126] = {Name =            "Mark of the Wild", Rank =  1, MaxLevel =  9, LevelBase =   "Self",},
    [ 5232] = {Name =            "Mark of the Wild", Rank =  2, MaxLevel = 19, LevelBase =   "Self",},
    [ 6756] = {Name =            "Mark of the Wild", Rank =  3, MaxLevel = 29, LevelBase =   "Self",},
    [ 5234] = {Name =            "Mark of the Wild", Rank =  4, MaxLevel = 39, LevelBase =   "Self",},
    [ 8907] = {Name =            "Mark of the Wild", Rank =  5, MaxLevel = 49, LevelBase =   "Self",},
    [ 9884] = {Name =            "Mark of the Wild", Rank =  6, MaxLevel = 59, LevelBase =   "Self",},
    [24752] = {Name =            "Mark of the Wild", Rank =  7, MaxLevel = 59, LevelBase =   "Self",},
    [ 9885] = {Name =            "Mark of the Wild", Rank =  7, MaxLevel = 69, LevelBase =   "Self",},
    [26990] = {Name =            "Mark of the Wild", Rank =  8, MaxLevel =  0, LevelBase =   "Self",},
    [39233] = {Name =            "Mark of the Wild", Rank =  8, MaxLevel =  0, LevelBase =   "Self",},
    [ 6807] = {Name =                        "Maul", Rank =  1, MaxLevel = 17, LevelBase =   "Self",},
    [ 6808] = {Name =                        "Maul", Rank =  2, MaxLevel = 25, LevelBase =   "Self",},
    [ 6809] = {Name =                        "Maul", Rank =  3, MaxLevel = 33, LevelBase =   "Self",},
    [ 8972] = {Name =                        "Maul", Rank =  4, MaxLevel = 41, LevelBase =   "Self",},
    [ 9745] = {Name =                        "Maul", Rank =  5, MaxLevel = 49, LevelBase =   "Self",},
    [ 9880] = {Name =                        "Maul", Rank =  6, MaxLevel = 57, LevelBase =   "Self",},
    [ 9881] = {Name =                        "Maul", Rank =  7, MaxLevel = 66, LevelBase =   "Self",},
    [26996] = {Name =                        "Maul", Rank =  8, MaxLevel =  0, LevelBase =   "Self",},
    [ 8921] = {Name =                    "Moonfire", Rank =  1, MaxLevel =  9, LevelBase =   "Self",},
    [20690] = {Name =                    "Moonfire", Rank =  1, MaxLevel =  9, LevelBase =   "Self",},
    [21669] = {Name =                    "Moonfire", Rank =  1, MaxLevel =  9, LevelBase =   "Self",},
    [ 8924] = {Name =                    "Moonfire", Rank =  2, MaxLevel = 15, LevelBase =   "Self",},
    [ 8925] = {Name =                    "Moonfire", Rank =  3, MaxLevel = 21, LevelBase =   "Self",},
    [ 8926] = {Name =                    "Moonfire", Rank =  4, MaxLevel = 27, LevelBase =   "Self",},
    [ 8927] = {Name =                    "Moonfire", Rank =  5, MaxLevel = 33, LevelBase =   "Self",},
    [ 8928] = {Name =                    "Moonfire", Rank =  6, MaxLevel = 39, LevelBase =   "Self",},
    [ 8929] = {Name =                    "Moonfire", Rank =  7, MaxLevel = 45, LevelBase =   "Self",},
    [ 9833] = {Name =                    "Moonfire", Rank =  8, MaxLevel = 51, LevelBase =   "Self",},
    [ 9834] = {Name =                    "Moonfire", Rank =  9, MaxLevel = 57, LevelBase =   "Self",},
    [ 9835] = {Name =                    "Moonfire", Rank = 10, MaxLevel = 62, LevelBase =   "Self",},
    [26987] = {Name =                    "Moonfire", Rank = 11, MaxLevel = 69, LevelBase =   "Self",},
    [26988] = {Name =                    "Moonfire", Rank = 12, MaxLevel =  0, LevelBase =   "Self",},
    [24907] = {Name =                "Moonkin Aura", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [16689] = {Name =              "Nature's Grasp", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [16810] = {Name =              "Nature's Grasp", Rank =  2, MaxLevel =  0, LevelBase =   "Self",},
    [16811] = {Name =              "Nature's Grasp", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [16812] = {Name =              "Nature's Grasp", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [16813] = {Name =              "Nature's Grasp", Rank =  5, MaxLevel =  0, LevelBase =   "Self",},
    [17329] = {Name =              "Nature's Grasp", Rank =  6, MaxLevel =  0, LevelBase =   "Self",},
    [27009] = {Name =              "Nature's Grasp", Rank =  7, MaxLevel =  0, LevelBase =   "Self",},
    [17116] = {Name =          "Nature's Swiftness", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [29274] = {Name =          "Nature's Swiftness", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [16864] = {Name =             "Omen of Clarity", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [21163] = {Name =              "Polished Armor", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [45838] = {Name =        "Possess Drake Immune", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [40282] = {Name =       "Possess Spirit Immune", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [39449] = {Name =                      "Pounce", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 9005] = {Name =                      "Pounce", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 9823] = {Name =                      "Pounce", Rank =  2, MaxLevel =  0, LevelBase =   "Self",},
    [ 9827] = {Name =                      "Pounce", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [27006] = {Name =                      "Pounce", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [ 5215] = {Name =                       "Prowl", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 6783] = {Name =                       "Prowl", Rank =  2, MaxLevel =  0, LevelBase =   "Self",},
    [ 9913] = {Name =                       "Prowl", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [32134] = {Name =                "Putrid Cloud", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [36332] = {Name =                        "Rake", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [24331] = {Name =                        "Rake", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [24332] = {Name =                        "Rake", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [27556] = {Name =                        "Rake", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [27638] = {Name =                        "Rake", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 1822] = {Name =                        "Rake", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 1823] = {Name =                        "Rake", Rank =  2, MaxLevel =  0, LevelBase =   "Self",},
    [ 1824] = {Name =                        "Rake", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [ 9904] = {Name =                        "Rake", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [27003] = {Name =                        "Rake", Rank =  5, MaxLevel =  0, LevelBase =   "Self",},
    [ 6785] = {Name =                      "Ravage", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 6787] = {Name =                      "Ravage", Rank =  2, MaxLevel =  0, LevelBase =   "Self",},
    [ 9866] = {Name =                      "Ravage", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [ 9867] = {Name =                      "Ravage", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [27005] = {Name =                      "Ravage", Rank =  5, MaxLevel =  0, LevelBase =   "Self",},
    [20484] = {Name =                     "Rebirth", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [20739] = {Name =                     "Rebirth", Rank =  2, MaxLevel =  0, LevelBase =   "Self",},
    [20742] = {Name =                     "Rebirth", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [20747] = {Name =                     "Rebirth", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [20748] = {Name =                     "Rebirth", Rank =  5, MaxLevel =  0, LevelBase =   "Self",},
    [26994] = {Name =                     "Rebirth", Rank =  6, MaxLevel =  0, LevelBase =   "Self",},
    [38324] = {Name =                "Regeneration", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [38325] = {Name =                "Regeneration", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 8936] = {Name =                    "Regrowth", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 8938] = {Name =                    "Regrowth", Rank =  2, MaxLevel =  0, LevelBase =   "Self",},
    [ 8939] = {Name =                    "Regrowth", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [ 8940] = {Name =                    "Regrowth", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [ 8941] = {Name =                    "Regrowth", Rank =  5, MaxLevel =  0, LevelBase =   "Self",},
    [ 9750] = {Name =                    "Regrowth", Rank =  6, MaxLevel =  0, LevelBase =   "Self",},
    [ 9856] = {Name =                    "Regrowth", Rank =  7, MaxLevel =  0, LevelBase =   "Self",},
    [ 9857] = {Name =                    "Regrowth", Rank =  8, MaxLevel =  0, LevelBase =   "Self",},
    [ 9858] = {Name =                    "Regrowth", Rank =  9, MaxLevel =  0, LevelBase =   "Self",},
    [26980] = {Name =                    "Regrowth", Rank = 10, MaxLevel =  0, LevelBase =   "Self",},
    [  774] = {Name =                "Rejuvenation", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 1058] = {Name =                "Rejuvenation", Rank =  2, MaxLevel =  0, LevelBase =   "Self",},
    [ 1430] = {Name =                "Rejuvenation", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [ 2090] = {Name =                "Rejuvenation", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [ 2091] = {Name =                "Rejuvenation", Rank =  5, MaxLevel =  0, LevelBase =   "Self",},
    [ 3627] = {Name =                "Rejuvenation", Rank =  6, MaxLevel =  0, LevelBase =   "Self",},
    [ 8910] = {Name =                "Rejuvenation", Rank =  7, MaxLevel =  0, LevelBase =   "Self",},
    [ 9839] = {Name =                "Rejuvenation", Rank =  8, MaxLevel =  0, LevelBase =   "Self",},
    [ 9840] = {Name =                "Rejuvenation", Rank =  9, MaxLevel =  0, LevelBase =   "Self",},
    [ 9841] = {Name =                "Rejuvenation", Rank = 10, MaxLevel =  0, LevelBase =   "Self",},
    [25299] = {Name =                "Rejuvenation", Rank = 11, MaxLevel =  0, LevelBase =   "Self",},
    [26981] = {Name =                "Rejuvenation", Rank = 12, MaxLevel =  0, LevelBase =   "Self",},
    [26982] = {Name =                "Rejuvenation", Rank = 13, MaxLevel =  0, LevelBase =   "Self",},
    [ 2782] = {Name =                "Remove Curse", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 1079] = {Name =                         "Rip", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 9492] = {Name =                         "Rip", Rank =  2, MaxLevel =  0, LevelBase =   "Self",},
    [ 9493] = {Name =                         "Rip", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [ 9752] = {Name =                         "Rip", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [ 9894] = {Name =                         "Rip", Rank =  5, MaxLevel =  0, LevelBase =   "Self",},
    [ 9896] = {Name =                         "Rip", Rank =  6, MaxLevel =  0, LevelBase =   "Self",},
    [27008] = {Name =                         "Rip", Rank =  7, MaxLevel =  0, LevelBase =   "Self",},
    [27555] = {Name =                       "Shred", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 5221] = {Name =                       "Shred", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 6800] = {Name =                       "Shred", Rank =  2, MaxLevel =  0, LevelBase =   "Self",},
    [ 8992] = {Name =                       "Shred", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [ 9829] = {Name =                       "Shred", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [ 9830] = {Name =                       "Shred", Rank =  5, MaxLevel =  0, LevelBase =   "Self",},
    [27001] = {Name =                       "Shred", Rank =  6, MaxLevel =  0, LevelBase =   "Self",},
    [27002] = {Name =                       "Shred", Rank =  7, MaxLevel =  0, LevelBase =   "Self",},
    [ 2908] = {Name =               "Soothe Animal", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 8955] = {Name =               "Soothe Animal", Rank =  2, MaxLevel =  0, LevelBase =   "Self",},
    [ 9901] = {Name =               "Soothe Animal", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [26995] = {Name =               "Soothe Animal", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [32740] = {Name =                      "Spikes", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [20687] = {Name =                    "Starfall", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [37124] = {Name =                    "Starfall", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 2912] = {Name =                    "Starfire", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [21668] = {Name =                    "Starfire", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [35243] = {Name =                    "Starfire", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [38935] = {Name =                    "Starfire", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 8949] = {Name =                    "Starfire", Rank =  2, MaxLevel =  0, LevelBase =   "Self",},
    [ 8950] = {Name =                    "Starfire", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [ 8951] = {Name =                    "Starfire", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [ 9875] = {Name =                    "Starfire", Rank =  5, MaxLevel =  0, LevelBase =   "Self",},
    [ 9876] = {Name =                    "Starfire", Rank =  6, MaxLevel =  0, LevelBase =   "Self",},
    [25298] = {Name =                    "Starfire", Rank =  7, MaxLevel =  0, LevelBase =   "Self",},
    [26986] = {Name =                    "Starfire", Rank =  8, MaxLevel =  0, LevelBase =   "Self",},
    [21187] = {Name =     "Stormpike Reputation +5", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [18562] = {Name =                   "Swiftmend", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [  779] = {Name =                       "Swipe", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [31279] = {Name =                       "Swipe", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [  780] = {Name =                       "Swipe", Rank =  2, MaxLevel =  0, LevelBase =   "Self",},
    [  769] = {Name =                       "Swipe", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [ 9754] = {Name =                       "Swipe", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [ 9908] = {Name =                       "Swipe", Rank =  5, MaxLevel =  0, LevelBase =   "Self",},
    [26997] = {Name =                       "Swipe", Rank =  6, MaxLevel =  0, LevelBase =   "Self",},
    [18960] = {Name =         "Teleport: Moonglade", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [24042] = {Name =                   "Test Maul", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [17154] = {Name =             "The Green Tower", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [22781] = {Name =                   "Thornling", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [  467] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [21335] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [21337] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [22128] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [22696] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [25640] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [25777] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [33907] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [34343] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [34663] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [35361] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [  782] = {Name =                      "Thorns", Rank =  2, MaxLevel =  0, LevelBase =   "Self",},
    [ 1075] = {Name =                      "Thorns", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [ 8914] = {Name =                      "Thorns", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [ 9756] = {Name =                      "Thorns", Rank =  5, MaxLevel =  0, LevelBase =   "Self",},
    [ 9910] = {Name =                      "Thorns", Rank =  6, MaxLevel =  0, LevelBase =   "Self",},
    [16877] = {Name =                      "Thorns", Rank =  6, MaxLevel =  0, LevelBase =   "Self",},
    [26992] = {Name =                      "Thorns", Rank =  7, MaxLevel =  0, LevelBase =   "Self",},
    [21791] = {Name =                 "Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [25817] = {Name =                 "Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [38659] = {Name =                 "Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [  740] = {Name =                 "Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [44203] = {Name =                 "Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [44205] = {Name =                 "Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [44206] = {Name =                 "Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [44207] = {Name =                 "Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [34550] = {Name =                 "Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [44208] = {Name =                 "Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 8918] = {Name =                 "Tranquility", Rank =  2, MaxLevel =  0, LevelBase =   "Self",},
    [ 9862] = {Name =                 "Tranquility", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [ 9863] = {Name =                 "Tranquility", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [26983] = {Name =                 "Tranquility", Rank =  5, MaxLevel =  0, LevelBase =   "Self",},
    [21793] = {Name =         "Twisted Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [29275] = {Name =              "Unstable Power", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [38162] = {Name =          "Unyielding Knights", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 5176] = {Name =                       "Wrath", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [17144] = {Name =                       "Wrath", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [18104] = {Name =                       "Wrath", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
    [ 5177] = {Name =                       "Wrath", Rank =  2, MaxLevel =  0, LevelBase =   "Self",},
    [ 5178] = {Name =                       "Wrath", Rank =  3, MaxLevel =  0, LevelBase =   "Self",},
    [ 5179] = {Name =                       "Wrath", Rank =  4, MaxLevel =  0, LevelBase =   "Self",},
    [ 5180] = {Name =                       "Wrath", Rank =  5, MaxLevel =  0, LevelBase =   "Self",},
    [ 6780] = {Name =                       "Wrath", Rank =  6, MaxLevel =  0, LevelBase =   "Self",},
    [ 8905] = {Name =                       "Wrath", Rank =  7, MaxLevel =  0, LevelBase =   "Self",},
    [ 9912] = {Name =                       "Wrath", Rank =  8, MaxLevel =  0, LevelBase =   "Self",},
    [26984] = {Name =                       "Wrath", Rank =  9, MaxLevel =  0, LevelBase =   "Self",},
    [26985] = {Name =                       "Wrath", Rank = 10, MaxLevel =  0, LevelBase =   "Self",},
    [32931] = {Name =                "Wrekt Visage", Rank =  1, MaxLevel =  0, LevelBase =   "Self",},
}