if GGWTest == nill then GGWTest = {} end

GGWTest.Classes =
{
    [1] =
    {
        ClassName = "Warrior",
        ClassColor = "FFC69B6D",
        SpellIDs =
        {

        },
    },
    [2] =
    {
        ClassName = "Paladin",
        ClassColor = "FFF48CBA",
        SpellIDs =
        {

        },
    },
    [3] =
    {
        ClassName =  "Hunter",
        ClassColor = "FFAAD372",
        SpellIDs =
        {

        },
    },
    [4] =
    {
        ClassName =   "Rogue",
        ClassColor = "FFFFF468",
        SpellIDs =
        {

        },
    },
    [5] =
    {
        ClassName =  "Priest",
        ClassColor = "FFFFFFFF",
        SpellIDs =
        {

        },
    },
    [7] =
    {
        ClassName =  "Shaman",
        ClassColor = "FF0070DD",
        SpellIDs =
        {

        },
    },
    [8] =
    {
        ClassName =    "Mage",
        ClassColor = "FF3FC7EB",
        SpellIDs =
        {

        },
    },
    [9] =
    {
        ClassName = "Warlock",
        ClassColor = "FF8788EE",
        SpellIDs =
        {

        },
    },
   [11] =
   {
       ClassName =   "Druid",
       ClassColor = "FFFF7C0A",
       SpellIDsOld =
       {
             [339] = {Name = "Entangling Roots", Rank = 1, MaxLevel =  1, LevelBase =   "Self"},

            --  Thorns is a buff, works for self or for target?
             [467] = {Name =           "Thorns", Rank = 1, MaxLevel =  1, LevelBase =   "Self"},
             [782] = {Name =           "Thorns", Rank = 2, MaxLevel =  1, LevelBase =   "Self"},

            [1126] = {Name = "Mark of the Wild", Rank = 1, MaxLevel =  1, LevelBase = "Target"},
            [5232] = {Name = "Mark of the Wild", Rank = 2, MaxLevel =  1, LevelBase = "Target"},

            [5176] = {Name =            "Wrath", Rank = 1, MaxLevel =  1, LevelBase =   "Self"},
            [5177] = {Name =            "Wrath", Rank = 2, MaxLevel =  1, LevelBase =   "Self"},
            [5178] = {Name =            "Wrath", Rank = 3, MaxLevel =  1, LevelBase =   "Self"},

            [8921] = {Name =         "Moonfire", Rank = 1, MaxLevel =  1, LevelBase =   "Self"},
            [8924] = {Name =         "Moonfire", Rank = 2, MaxLevel =  1, LevelBase =   "Self"},
        },
        SpellIDs =
        {
            [ 2893] = {Name =              "Abolish Poison", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [22812] = {Name =                    "Barkskin", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 5211] = {Name =                        "Bash", Rank =  1, MaxLevel = 29, LevelBase =   "Self", Ignored = false,},
            [ 6798] = {Name =                        "Bash", Rank =  2, MaxLevel = 45, LevelBase =   "Self", Ignored = false,},
            [ 8983] = {Name =                        "Bash", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [33009] = {Name =              "Blinding Light", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [25999] = {Name =                 "Boar Charge", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [33908] = {Name =              "Burning Spikes", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 1082] = {Name =                        "Claw", Rank =  1, MaxLevel = 27, LevelBase =   "Self", Ignored = false,},
            [31289] = {Name =                        "Claw", Rank =  1, MaxLevel = 27, LevelBase =   "Self", Ignored = false,},
            [ 3029] = {Name =                        "Claw", Rank =  2, MaxLevel = 37, LevelBase =   "Self", Ignored = false,},
            [ 5201] = {Name =                        "Claw", Rank =  3, MaxLevel = 47, LevelBase =   "Self", Ignored = false,},
            [ 9849] = {Name =                        "Claw", Rank =  4, MaxLevel = 57, LevelBase =   "Self", Ignored = false,},
            [ 9850] = {Name =                        "Claw", Rank =  5, MaxLevel = 66, LevelBase =   "Self", Ignored = false,},
            [27000] = {Name =                        "Claw", Rank =  6, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [16870] = {Name =                "Clearcasting", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [34071] = {Name =                 "Combo Point", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [32618] = {Name =        "Cosmetic Nature Cast", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [38326] = {Name = "Crit Threat Reduction Melee", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [38327] = {Name = "Crit Threat Reduction Spell", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 8946] = {Name =                 "Cure Poison", Rank =  1, MaxLevel = 25, LevelBase =   "Self", Ignored = false,},
            [33786] = {Name =                     "Cyclone", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [   99] = {Name =           "Demoralizing Roar", Rank =  1, MaxLevel = 19, LevelBase =   "Self", Ignored = false,},
            [ 1735] = {Name =           "Demoralizing Roar", Rank =  2, MaxLevel = 31, LevelBase =   "Self", Ignored = false,},
            [ 9490] = {Name =           "Demoralizing Roar", Rank =  3, MaxLevel = 41, LevelBase =   "Self", Ignored = false,},
            [ 9747] = {Name =           "Demoralizing Roar", Rank =  4, MaxLevel = 51, LevelBase =   "Self", Ignored = false,},
            [ 9898] = {Name =           "Demoralizing Roar", Rank =  5, MaxLevel = 61, LevelBase =   "Self", Ignored = false,},
            [26998] = {Name =           "Demoralizing Roar", Rank =  6, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [25059] = {Name =                  "Dmg Shield", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [26666] = {Name =                 "Dmg Shield2", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 5229] = {Name =                      "Enrage", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [  339] = {Name =            "Entangling Roots", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [19975] = {Name =            "Entangling Roots", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [40363] = {Name =            "Entangling Roots", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 1062] = {Name =            "Entangling Roots", Rank =  2, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [19974] = {Name =            "Entangling Roots", Rank =  2, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 5195] = {Name =            "Entangling Roots", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [19973] = {Name =            "Entangling Roots", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 5196] = {Name =            "Entangling Roots", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [19972] = {Name =            "Entangling Roots", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9852] = {Name =            "Entangling Roots", Rank =  5, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [19971] = {Name =            "Entangling Roots", Rank =  5, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9853] = {Name =            "Entangling Roots", Rank =  6, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [19970] = {Name =            "Entangling Roots", Rank =  6, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [26989] = {Name =            "Entangling Roots", Rank =  7, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [27010] = {Name =            "Entangling Roots", Rank =  7, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [27546] = {Name =          "Faerie Dragon Form", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [  770] = {Name =                 "Faerie Fire", Rank =  1, MaxLevel = 29, LevelBase =   "Self", Ignored = false,},
            [  778] = {Name =                 "Faerie Fire", Rank =  2, MaxLevel = 41, LevelBase =   "Self", Ignored = false,},
            [ 9749] = {Name =                 "Faerie Fire", Rank =  3, MaxLevel = 53, LevelBase =   "Self", Ignored = false,},
            [ 9907] = {Name =                 "Faerie Fire", Rank =  4, MaxLevel = 65, LevelBase =   "Self", Ignored = false,},
            [26993] = {Name =                 "Faerie Fire", Rank =  5, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [16857] = {Name =         "Faerie Fire (Feral)", Rank =  1, MaxLevel = 29, LevelBase =   "Self", Ignored = false,},
            [17390] = {Name =         "Faerie Fire (Feral)", Rank =  2, MaxLevel = 41, LevelBase =   "Self", Ignored = false,},
            [17391] = {Name =         "Faerie Fire (Feral)", Rank =  3, MaxLevel = 53, LevelBase =   "Self", Ignored = false,},
            [17392] = {Name =         "Faerie Fire (Feral)", Rank =  4, MaxLevel = 65, LevelBase =   "Self", Ignored = false,},
            [27011] = {Name =         "Faerie Fire (Feral)", Rank =  5, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [38333] = {Name =                   "Fecundity", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [16979] = {Name =                "Feral Charge", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [19675] = {Name =         "Feral Charge Effect", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [45334] = {Name =         "Feral Charge Effect", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [24867] = {Name =  "Feral Swiftness Passive 1a", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [24864] = {Name =  "Feral Swiftness Passive 2a", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [22568] = {Name =              "Ferocious Bite", Rank =  1, MaxLevel = 39, LevelBase =   "Self", Ignored = false,},
            [22827] = {Name =              "Ferocious Bite", Rank =  2, MaxLevel = 47, LevelBase =   "Self", Ignored = false,},
            [22828] = {Name =              "Ferocious Bite", Rank =  3, MaxLevel = 55, LevelBase =   "Self", Ignored = false,},
            [22829] = {Name =              "Ferocious Bite", Rank =  4, MaxLevel = 59, LevelBase =   "Self", Ignored = false,},
            [31018] = {Name =              "Ferocious Bite", Rank =  5, MaxLevel = 62, LevelBase =   "Self", Ignored = false,},
            [24248] = {Name =              "Ferocious Bite", Rank =  6, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [33831] = {Name =             "Force of Nature", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [22842] = {Name =       "Frenzied Regeneration", Rank =  1, MaxLevel = 45, LevelBase =   "Self", Ignored = false,},
            [22895] = {Name =       "Frenzied Regeneration", Rank =  2, MaxLevel = 55, LevelBase =   "Self", Ignored = false,},
            [22896] = {Name =       "Frenzied Regeneration", Rank =  3, MaxLevel = 64, LevelBase =   "Self", Ignored = false,},
            [26999] = {Name =       "Frenzied Regeneration", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [21849] = {Name =            "Gift of the Wild", Rank =  1, MaxLevel = 59, LevelBase =   "Self", Ignored = false,},
            [21850] = {Name =            "Gift of the Wild", Rank =  2, MaxLevel = 69, LevelBase =   "Self", Ignored = false,},
            [26991] = {Name =            "Gift of the Wild", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 6795] = {Name =                       "Growl", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [39270] = {Name =                       "Growl", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 5185] = {Name =               "Healing Touch", Rank =  1, MaxLevel =  7, LevelBase =   "Self", Ignored =  true,},
            [ 5186] = {Name =               "Healing Touch", Rank =  2, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 5187] = {Name =               "Healing Touch", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 5188] = {Name =               "Healing Touch", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 5189] = {Name =               "Healing Touch", Rank =  5, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 6778] = {Name =               "Healing Touch", Rank =  6, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 8903] = {Name =               "Healing Touch", Rank =  7, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 9758] = {Name =               "Healing Touch", Rank =  8, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 9888] = {Name =               "Healing Touch", Rank =  9, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 9889] = {Name =               "Healing Touch", Rank = 10, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [25297] = {Name =               "Healing Touch", Rank = 11, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [26978] = {Name =               "Healing Touch", Rank = 12, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [26979] = {Name =               "Healing Touch", Rank = 13, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 2637] = {Name =                   "Hibernate", Rank =  1, MaxLevel = 37, LevelBase =   "Self", Ignored = false,},
            [18657] = {Name =                   "Hibernate", Rank =  2, MaxLevel = 57, LevelBase =   "Self", Ignored = false,},
            [18658] = {Name =                   "Hibernate", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [27530] = {Name =                   "Hurricane", Rank =  1, MaxLevel = 39, LevelBase =   "Self", Ignored = false,},
            [32717] = {Name =                   "Hurricane", Rank =  1, MaxLevel = 39, LevelBase =   "Self", Ignored = false,},
            [16914] = {Name =                   "Hurricane", Rank =  1, MaxLevel = 49, LevelBase =   "Self", Ignored = false,},
            [42231] = {Name =                   "Hurricane", Rank =  1, MaxLevel = 49, LevelBase =   "Self", Ignored = false,},
            [17401] = {Name =                   "Hurricane", Rank =  2, MaxLevel = 59, LevelBase =   "Self", Ignored = false,},
            [42232] = {Name =                   "Hurricane", Rank =  2, MaxLevel = 59, LevelBase =   "Self", Ignored = false,},
            [17402] = {Name =                   "Hurricane", Rank =  3, MaxLevel = 69, LevelBase =   "Self", Ignored = false,},
            [42233] = {Name =                   "Hurricane", Rank =  3, MaxLevel = 69, LevelBase =   "Self", Ignored = false,},
            [27012] = {Name =                   "Hurricane", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [42230] = {Name =                   "Hurricane", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [29166] = {Name =                   "Innervate", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 5570] = {Name =                "Insect Swarm", Rank =  1, MaxLevel = 29, LevelBase =   "Self", Ignored = false,},
            [24974] = {Name =                "Insect Swarm", Rank =  2, MaxLevel = 39, LevelBase =   "Self", Ignored = false,},
            [24975] = {Name =                "Insect Swarm", Rank =  3, MaxLevel = 49, LevelBase =   "Self", Ignored = false,},
            [24976] = {Name =                "Insect Swarm", Rank =  4, MaxLevel = 59, LevelBase =   "Self", Ignored = false,},
            [24977] = {Name =                "Insect Swarm", Rank =  5, MaxLevel = 69, LevelBase =   "Self", Ignored = false,},
            [27013] = {Name =                "Insect Swarm", Rank =  6, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [41357] = {Name =            "L1 Arcane Charge", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [41349] = {Name =            "L4 Arcane Charge", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [41360] = {Name =            "L5 Arcane Charge", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [33745] = {Name =                    "Lacerate", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [33763] = {Name =                   "Lifebloom", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [33778] = {Name =                   "Lifebloom", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [22570] = {Name =                        "Maim", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [19634] = {Name =           "Mana Rejuvenation", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [39164] = {Name =                      "Mangle", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [31041] = {Name =                      "Mangle", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [44955] = {Name =                      "Mangle", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [33878] = {Name =               "Mangle (Bear)", Rank =  1, MaxLevel = 57, LevelBase =   "Self", Ignored = false,},
            [33986] = {Name =               "Mangle (Bear)", Rank =  2, MaxLevel = 67, LevelBase =   "Self", Ignored = false,},
            [33987] = {Name =               "Mangle (Bear)", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [33876] = {Name =                "Mangle (Cat)", Rank =  1, MaxLevel = 57, LevelBase =   "Self", Ignored = false,},
            [33982] = {Name =                "Mangle (Cat)", Rank =  2, MaxLevel = 67, LevelBase =   "Self", Ignored = false,},
            [33983] = {Name =                "Mangle (Cat)", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 1126] = {Name =            "Mark of the Wild", Rank =  1, MaxLevel =  9, LevelBase =   "Self", Ignored = false,},
            [ 5232] = {Name =            "Mark of the Wild", Rank =  2, MaxLevel = 19, LevelBase =   "Self", Ignored = false,},
            [ 6756] = {Name =            "Mark of the Wild", Rank =  3, MaxLevel = 29, LevelBase =   "Self", Ignored = false,},
            [ 5234] = {Name =            "Mark of the Wild", Rank =  4, MaxLevel = 39, LevelBase =   "Self", Ignored = false,},
            [ 8907] = {Name =            "Mark of the Wild", Rank =  5, MaxLevel = 49, LevelBase =   "Self", Ignored = false,},
            [ 9884] = {Name =            "Mark of the Wild", Rank =  6, MaxLevel = 59, LevelBase =   "Self", Ignored = false,},
            [24752] = {Name =            "Mark of the Wild", Rank =  7, MaxLevel = 59, LevelBase =   "Self", Ignored = false,},
            [ 9885] = {Name =            "Mark of the Wild", Rank =  7, MaxLevel = 69, LevelBase =   "Self", Ignored = false,},
            [26990] = {Name =            "Mark of the Wild", Rank =  8, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [39233] = {Name =            "Mark of the Wild", Rank =  8, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 6807] = {Name =                        "Maul", Rank =  1, MaxLevel = 17, LevelBase =   "Self", Ignored = false,},
            [ 6808] = {Name =                        "Maul", Rank =  2, MaxLevel = 25, LevelBase =   "Self", Ignored = false,},
            [ 6809] = {Name =                        "Maul", Rank =  3, MaxLevel = 33, LevelBase =   "Self", Ignored = false,},
            [ 8972] = {Name =                        "Maul", Rank =  4, MaxLevel = 41, LevelBase =   "Self", Ignored = false,},
            [ 9745] = {Name =                        "Maul", Rank =  5, MaxLevel = 49, LevelBase =   "Self", Ignored = false,},
            [ 9880] = {Name =                        "Maul", Rank =  6, MaxLevel = 57, LevelBase =   "Self", Ignored = false,},
            [ 9881] = {Name =                        "Maul", Rank =  7, MaxLevel = 66, LevelBase =   "Self", Ignored = false,},
            [26996] = {Name =                        "Maul", Rank =  8, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 8921] = {Name =                    "Moonfire", Rank =  1, MaxLevel =  9, LevelBase =   "Self", Ignored =  true,},
            [20690] = {Name =                    "Moonfire", Rank =  1, MaxLevel =  9, LevelBase =   "Self", Ignored = false,},
            [21669] = {Name =                    "Moonfire", Rank =  1, MaxLevel =  9, LevelBase =   "Self", Ignored = false,},
            [ 8924] = {Name =                    "Moonfire", Rank =  2, MaxLevel = 15, LevelBase =   "Self", Ignored = false,},
            [ 8925] = {Name =                    "Moonfire", Rank =  3, MaxLevel = 21, LevelBase =   "Self", Ignored = false,},
            [ 8926] = {Name =                    "Moonfire", Rank =  4, MaxLevel = 27, LevelBase =   "Self", Ignored = false,},
            [ 8927] = {Name =                    "Moonfire", Rank =  5, MaxLevel = 33, LevelBase =   "Self", Ignored = false,},
            [ 8928] = {Name =                    "Moonfire", Rank =  6, MaxLevel = 39, LevelBase =   "Self", Ignored = false,},
            [ 8929] = {Name =                    "Moonfire", Rank =  7, MaxLevel = 45, LevelBase =   "Self", Ignored = false,},
            [ 9833] = {Name =                    "Moonfire", Rank =  8, MaxLevel = 51, LevelBase =   "Self", Ignored = false,},
            [ 9834] = {Name =                    "Moonfire", Rank =  9, MaxLevel = 57, LevelBase =   "Self", Ignored = false,},
            [ 9835] = {Name =                    "Moonfire", Rank = 10, MaxLevel = 62, LevelBase =   "Self", Ignored = false,},
            [26987] = {Name =                    "Moonfire", Rank = 11, MaxLevel = 69, LevelBase =   "Self", Ignored = false,},
            [26988] = {Name =                    "Moonfire", Rank = 12, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [24907] = {Name =                "Moonkin Aura", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [16689] = {Name =              "Nature's Grasp", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [16810] = {Name =              "Nature's Grasp", Rank =  2, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [16811] = {Name =              "Nature's Grasp", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [16812] = {Name =              "Nature's Grasp", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [16813] = {Name =              "Nature's Grasp", Rank =  5, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [17329] = {Name =              "Nature's Grasp", Rank =  6, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [27009] = {Name =              "Nature's Grasp", Rank =  7, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [17116] = {Name =          "Nature's Swiftness", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [29274] = {Name =          "Nature's Swiftness", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [16864] = {Name =             "Omen of Clarity", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [21163] = {Name =              "Polished Armor", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [45838] = {Name =        "Possess Drake Immune", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [40282] = {Name =       "Possess Spirit Immune", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [39449] = {Name =                      "Pounce", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9005] = {Name =                      "Pounce", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9823] = {Name =                      "Pounce", Rank =  2, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9827] = {Name =                      "Pounce", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [27006] = {Name =                      "Pounce", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 5215] = {Name =                       "Prowl", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 6783] = {Name =                       "Prowl", Rank =  2, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9913] = {Name =                       "Prowl", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [32134] = {Name =                "Putrid Cloud", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [36332] = {Name =                        "Rake", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [24331] = {Name =                        "Rake", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [24332] = {Name =                        "Rake", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [27556] = {Name =                        "Rake", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [27638] = {Name =                        "Rake", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 1822] = {Name =                        "Rake", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 1823] = {Name =                        "Rake", Rank =  2, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 1824] = {Name =                        "Rake", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9904] = {Name =                        "Rake", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [27003] = {Name =                        "Rake", Rank =  5, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 6785] = {Name =                      "Ravage", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 6787] = {Name =                      "Ravage", Rank =  2, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9866] = {Name =                      "Ravage", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9867] = {Name =                      "Ravage", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [27005] = {Name =                      "Ravage", Rank =  5, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [20484] = {Name =                     "Rebirth", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [20739] = {Name =                     "Rebirth", Rank =  2, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [20742] = {Name =                     "Rebirth", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [20747] = {Name =                     "Rebirth", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [20748] = {Name =                     "Rebirth", Rank =  5, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [26994] = {Name =                     "Rebirth", Rank =  6, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [38324] = {Name =                "Regeneration", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [38325] = {Name =                "Regeneration", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 8936] = {Name =                    "Regrowth", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 8938] = {Name =                    "Regrowth", Rank =  2, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 8939] = {Name =                    "Regrowth", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 8940] = {Name =                    "Regrowth", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 8941] = {Name =                    "Regrowth", Rank =  5, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 9750] = {Name =                    "Regrowth", Rank =  6, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 9856] = {Name =                    "Regrowth", Rank =  7, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 9857] = {Name =                    "Regrowth", Rank =  8, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 9858] = {Name =                    "Regrowth", Rank =  9, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [26980] = {Name =                    "Regrowth", Rank = 10, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [  774] = {Name =                "Rejuvenation", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 1058] = {Name =                "Rejuvenation", Rank =  2, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 1430] = {Name =                "Rejuvenation", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 2090] = {Name =                "Rejuvenation", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 2091] = {Name =                "Rejuvenation", Rank =  5, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 3627] = {Name =                "Rejuvenation", Rank =  6, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 8910] = {Name =                "Rejuvenation", Rank =  7, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 9839] = {Name =                "Rejuvenation", Rank =  8, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 9840] = {Name =                "Rejuvenation", Rank =  9, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 9841] = {Name =                "Rejuvenation", Rank = 10, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [25299] = {Name =                "Rejuvenation", Rank = 11, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [26981] = {Name =                "Rejuvenation", Rank = 12, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [26982] = {Name =                "Rejuvenation", Rank = 13, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 2782] = {Name =                "Remove Curse", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 1079] = {Name =                         "Rip", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9492] = {Name =                         "Rip", Rank =  2, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9493] = {Name =                         "Rip", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9752] = {Name =                         "Rip", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9894] = {Name =                         "Rip", Rank =  5, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9896] = {Name =                         "Rip", Rank =  6, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [27008] = {Name =                         "Rip", Rank =  7, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [27555] = {Name =                       "Shred", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 5221] = {Name =                       "Shred", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 6800] = {Name =                       "Shred", Rank =  2, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 8992] = {Name =                       "Shred", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9829] = {Name =                       "Shred", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9830] = {Name =                       "Shred", Rank =  5, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [27001] = {Name =                       "Shred", Rank =  6, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [27002] = {Name =                       "Shred", Rank =  7, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 2908] = {Name =               "Soothe Animal", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 8955] = {Name =               "Soothe Animal", Rank =  2, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9901] = {Name =               "Soothe Animal", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [26995] = {Name =               "Soothe Animal", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [32740] = {Name =                      "Spikes", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [20687] = {Name =                    "Starfall", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [37124] = {Name =                    "Starfall", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 2912] = {Name =                    "Starfire", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [21668] = {Name =                    "Starfire", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [35243] = {Name =                    "Starfire", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [38935] = {Name =                    "Starfire", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 8949] = {Name =                    "Starfire", Rank =  2, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 8950] = {Name =                    "Starfire", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 8951] = {Name =                    "Starfire", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9875] = {Name =                    "Starfire", Rank =  5, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9876] = {Name =                    "Starfire", Rank =  6, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [25298] = {Name =                    "Starfire", Rank =  7, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [26986] = {Name =                    "Starfire", Rank =  8, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [21187] = {Name =     "Stormpike Reputation +5", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [18562] = {Name =                   "Swiftmend", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [  779] = {Name =                       "Swipe", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [31279] = {Name =                       "Swipe", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [  780] = {Name =                       "Swipe", Rank =  2, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [  769] = {Name =                       "Swipe", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9754] = {Name =                       "Swipe", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9908] = {Name =                       "Swipe", Rank =  5, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [26997] = {Name =                       "Swipe", Rank =  6, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [18960] = {Name =         "Teleport: Moonglade", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [24042] = {Name =                   "Test Maul", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [17154] = {Name =             "The Green Tower", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [22781] = {Name =                   "Thornling", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [  467] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [21335] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [21337] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [22128] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [22696] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [25640] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [25777] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [33907] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [34343] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [34663] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [35361] = {Name =                      "Thorns", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [  782] = {Name =                      "Thorns", Rank =  2, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 1075] = {Name =                      "Thorns", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 8914] = {Name =                      "Thorns", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9756] = {Name =                      "Thorns", Rank =  5, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9910] = {Name =                      "Thorns", Rank =  6, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [16877] = {Name =                      "Thorns", Rank =  6, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [26992] = {Name =                      "Thorns", Rank =  7, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [21791] = {Name =                 "Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [25817] = {Name =                 "Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [38659] = {Name =                 "Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [  740] = {Name =                 "Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [44203] = {Name =                 "Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [44205] = {Name =                 "Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [44206] = {Name =                 "Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [44207] = {Name =                 "Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [34550] = {Name =                 "Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [44208] = {Name =                 "Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 8918] = {Name =                 "Tranquility", Rank =  2, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 9862] = {Name =                 "Tranquility", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [ 9863] = {Name =                 "Tranquility", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [26983] = {Name =                 "Tranquility", Rank =  5, MaxLevel =  0, LevelBase =   "Self", Ignored =  true,},
            [21793] = {Name =         "Twisted Tranquility", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [29275] = {Name =              "Unstable Power", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [38162] = {Name =          "Unyielding Knights", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 5176] = {Name =                       "Wrath", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [17144] = {Name =                       "Wrath", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [18104] = {Name =                       "Wrath", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 5177] = {Name =                       "Wrath", Rank =  2, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 5178] = {Name =                       "Wrath", Rank =  3, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 5179] = {Name =                       "Wrath", Rank =  4, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 5180] = {Name =                       "Wrath", Rank =  5, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 6780] = {Name =                       "Wrath", Rank =  6, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 8905] = {Name =                       "Wrath", Rank =  7, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [ 9912] = {Name =                       "Wrath", Rank =  8, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [26984] = {Name =                       "Wrath", Rank =  9, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [26985] = {Name =                       "Wrath", Rank = 10, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
            [32931] = {Name =                "Wrekt Visage", Rank =  1, MaxLevel =  0, LevelBase =   "Self", Ignored = false,},
        }
    },
}